spring.application.name=lovegods

email.from.default=hello@exquisiteloop.com
email.to.default=hello@exquisiteloop.com
email.error=hello@exquisiteloop.com
email.support=support@exquisiteloop.com


spring.mail.host=${LOVEGODS_SMTP_HOST}
spring.mail.port=${LOVEGODS_SMTP_PORT}
spring.mail.protocol=smtps
spring.mail.username=${LOVEGODS_SMTP_USER}
spring.mail.password=${LOVEGODS_SMTP_PASS}

google.analytics.id=${LOVEGODS_ANALYTICS_ID:}

google.recaptcha.sitekey=${LOVEGODS_RECAPTCHA_SITE_KEY}
google.recaptcha.secretkey=${LOVEGODS_RECAPTCHA_SECRET_KEY}