spring.application.name=Lovegods

# Disable template caching during development (re-enable in prod)
spring.thymeleaf.cache=false

email.from.default=hello@exquisiteloop.com
email.to.default=rich.thibault@gmail.com
email.error=rich.thibault@gmail.com

spring.mail.host=${LOVEGODS_SMTP_HOST}
spring.mail.port=${LOVEGODS_SMTP_PORT}
spring.mail.protocol=smtps
spring.mail.username=${LOVEGODS_SMTP_USER}
spring.mail.password=${LOVEGODS_SMTP_PASS}

google.analytics.id=${LOVEGODS_ANALYTICS_ID:}

google.recaptcha.key.site=${LOVEGODS_RECAPTCHA_SITEKEY}
google.recaptcha.key.secret=${LOVEGODS_RECAPTCHA_SECRETKEY}